import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-mongodb'
import { commitTransaction, initTransaction, Payload, PayloadRequest } from 'payload'
import path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const mediaFolder = path.resolve(__dirname, 'media')

const adminUserEmail = 'oemer.aran95+bdw2@gmail.com'

export async function up({ payload, req }: MigrateUpArgs): Promise<void> {
  await initTransaction(req)
  req.context = { skipRevalidation: true }
  await seedData({ payload, req })
  await commitTransaction(req)
}

export async function down({ payload, req }: MigrateDownArgs): Promise<void> {
  const admin = await payload.find({
    collection: 'users',
    where: {
      email: { equals: adminUserEmail },
    },
    req,
  })

  if (admin.totalDocs > 0) {
    await payload.delete({
      collection: 'users',
      id: admin.docs[0].id,
      req,
    })
  }

  await payload.delete({
    collection: 'media',
    where: {
      id: {
        exists: true,
      },
    },
    req,
  })
}

async function seedData({ payload, req }: MigrateUpArgs) {
  await payload.create({
    collection: 'users',
    data: {
      name: 'A3 Admin',
      email: adminUserEmail,
      password: 'changeme',
    },
    req,
  })

  payload.logger.info(`— Seeding media...`)

  const heroCouple = await uploadMedia({
    payload,
    req,
    fileName: 'hero-couple.jpg',
  })

  const locationImage1 = await uploadMedia({
    payload,
    req,
    fileName: 'gardos-tower.webp',
  })

  const locationImage2 = await uploadMedia({
    payload,
    req,
    fileName: 'gardos-tower-outside.jpg',
  })

  const locationImage3 = await uploadMedia({
    payload,
    req,
    fileName: 'gardos-tower-outside-2.jpg',
  })

  // Seed the start-page global for each language locale
  payload.logger.info(`— Seeding start-page for de...`)
  await payload.updateGlobal({
    slug: 'start-page',
    locale: 'de',
    publishSpecificLocale: 'de',
    data: {
      general: {
        weddingDate: '2025-06-14',
        participationDeadlineInformation: 'Bitte bestätigt eure Teilnahme bis zum {{deadlineDate}}',
        participationDeadline: '2025-01-31',
        phoneNumber: '+49 4954 3450492',
      },
      start: {
        backgroundImage: heroCouple.id,
        title: 'Begüm & Daniel',
        description: 'Wir freuen uns darauf, unseren besonderen Tag mit euch zu teilen!',
        buttonText: 'Teilnahme bestätigen',
      },
      information: {
        title: 'Information',
        subtitle:
          'Hier findest du hilfreiche Informationen rund um die Hauptstadt Serbiens – sowohl für die Planung im Vorfeld als auch für die Zeit danach.',
        description: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Belgrad entdecken: Sehenswürdigkeiten, Shopping und Taxi-Apps',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: 'center',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h1',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Belgrad, die lebendige Hauptstadt Serbiens, erwartet dich mit beeindruckenden Sehenswürdigkeiten, einer faszinierenden Kultur und tollen Shopping-Möglichkeiten. Hier sind einige Highlights, die du dir während deines Aufenthalts unbedingt ansehen solltest:',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Kalemegdan-Festung und Park',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/Q15gp1b56zwxJk9r5',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d017e',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Die historische Festung bietet dir eine beeindruckende Aussicht auf die Donau und Save und ist von einem wunderschönen Park umgeben – perfekt zum Spazieren und Entspannen',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 1,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Skadarlija – das Künstlerviertel',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/5LY3Rqs4wE1rEf9E8',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d017f',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Skadarlija bezaubert mit Kopfsteinpflaster, traditionellen Restaurants und einer besonderen Künstleratmosphäre. Hier kannst du die Kultur Belgrads hautnah erleben.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 2,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Sankt-Sava-Tempel',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://g.co/kgs/QuTW3Sc',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0180',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Die größte orthodoxe Kirche der Welt ist ein beeindruckendes Wahrzeichen und ein spirituelles Zentrum, das du dir auf keinen Fall entgehen lassen solltest.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 3,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Knez Mihailova Straße',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/GP7XoZ29xdsnAv1u5',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0181',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Diese belebte Fußgängerzone ist ideal zum Bummeln und Shoppen und bietet viele gemütliche Cafés und Restaurants.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 4,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Galerija Shopping Mall',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://g.co/kgs/rQzisLq',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0183',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Die ',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Galerija Belgrade',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ist das größte Einkaufszentrum auf dem Balkan und bietet dir eine riesige Auswahl an internationalen und lokalen Marken, hervorragende Restaurants und Unterhaltung für alle Altersgruppen – perfekt für einen ausgiebigen Shopping-Tag.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 5,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'list',
                version: 1,
                listType: 'bullet',
                start: 1,
                tag: 'ul',
              },
              {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 1,
                textStyle: '',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Taxi in Belgrad: Die richtige App',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h2',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Um dich bequem durch Belgrad zu bewegen, empfehlen wir dir die ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Pink Taxi App',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      doc: null,
                      linkType: 'custom',
                      newTab: false,
                      url: 'https://apps.apple.com/app/pink-taxi/id1459526702',
                    },
                    id: '67210ad5392660db554d0184',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' (',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'iOS',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://apps.apple.com/us/app/pink-taxi-beograd/id1446423607',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210ad5392660db554d0185',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' | ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Android',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://play.google.com/store/apps/details?id=com.autocab.taxibooker.pinktaxi.serbia&hl=de&pli=1',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210ad5392660db554d0186',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '). Die App ist eine zuverlässige und sichere Option, um Taxis in Belgrad zu buchen. ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Tipp:',
                    type: 'text',
                    version: 1,
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Am Samstag kann es wegen der hohen Nachfrage schwierig sein, ein Taxi zu bekommen – plane daher am besten etwas Zeit ein oder buche im Voraus.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Eine weitere gute Wahl ist die ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Yandex Go App',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      doc: null,
                      linkType: 'custom',
                      newTab: false,
                      url: 'https://yandex.com/',
                    },
                    id: '67210b2b392660db554d0188',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' (',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'iOS',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://apps.apple.com/de/app/yandex-go-taxi-food-delivery/id472650686',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210b2b392660db554d0189',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' | ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Android',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://play.google.com/store/apps/details?id=ru.yandex.taxi&hl=de',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210b2b392660db554d018a',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '), die ebenfalls Festpreise und eine einfache Zahlung per App bietet.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                format: '',
                type: 'upload',
                version: 1,
                id: heroCouple.id,
                fields: null,
                relationTo: 'media',
                value: heroCouple.id,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      pariticipation: {
        title: 'Wir freuen uns auf Euch!',
        subtitle:
          'Bitte gib hier kurz an, wer an der Feier teilnimmt und wer zum Friseur/Makeup mitkommen möchte.',
        form: {
          participants: 'Teilnehmer',
          addParticipant: 'Teilnehmer hinzufügen',
          paricipantPlaceholder: 'Name des Teilnehmers',
          paricipantKidPlaceholder: 'Name des Kindes',

          participantKid: 'Teilnehmer Kind (bis 3 Jahre)',
          addParticipantKid: 'Kind hinzufügen',
          makeupHairInfo: '60€ pro Person.',
          makeupHairPrice: 60,
          hairdresser: 'Friseur',
          makeup: 'Makeup',
          buttonText: 'Teilnahme bestätigen',
          nameMissing: 'Bitte gib einen Namen ein.',
          unexpectedError:
            'Ein unerwarteter Fehler ist aufgetreten. Bitte schreib uns auf WhatsApp oder ruf uns an.',
        },
        formSuccess: {
          backToStartPage: 'Zurück zur Startseite',
          title: 'Teilnahme bestätigt',
          subtitle:
            'Wir freuen uns auf dich! Falls sich etwas an deiner Teilnahme ändert, gib uns einfach Bescheid.',
        },
      },
      countdown: {
        title: 'Bald ist es soweit!',
        days: 'Tage',
        hours: 'Stunden',
        minutes: 'Minuten',
        seconds: 'Sekunden',
      },
      location: {
        image1: locationImage1.id,
        image2: locationImage2.id,
        image3: locationImage3.id,
        title: 'Location',
        name: 'Restaurant Gardos',
        address: 'Grobljanska BB, Belgrad 11080, Serbien',
        buttonText: 'Google Maps',
        time: '17:00 - 01:00',
        mapsLink:
          'https://www.google.com/maps/place/Restaurant+Gardos/@44.848237,20.4044287,16z/data=!3m1!4b1!4m6!3m5!1s0x475a65a0fd0e7c1d:0xba29e72b79de3ac!8m2!3d44.8482371!4d20.409305!16s%2Fg%2F11c5zxfc_d?entry=ttu&g_ep=EgoyMDI0MTAxNi4wIKXMDSoASAFQAw%3D%3D',
      },
      footer: {
        title: 'Noch fragen?',
        subtitle: 'Ruft uns an oder schreibt uns einfach auf WhatsApp!',
      },
    },
    req,
  })

  payload.logger.info(`— Seeding start-page for tr...`)
  await payload.updateGlobal({
    slug: 'start-page',
    locale: 'tr',
    publishSpecificLocale: 'tr',
    data: {
      general: {
        weddingDate: '2025-06-14',
        participationDeadlineInformation:
          'Lütfen katılımınızı {{deadlineDate}} tarihine kadar onaylayın',
        participationDeadline: '2025-01-31',
        phoneNumber: '+49 4954 3450492',
      },
      start: {
        backgroundImage: heroCouple.id,
        title: 'Begüm & Daniel',
        description: 'Özel günümüzü sizinle paylaşmayı dört gözle bekliyoruz!',
        buttonText: 'Katılımı onayla',
      },
      information: {
        title: 'Bilgi',
        subtitle:
          'Burada Sırbistan’ın başkenti hakkında faydalı bilgiler bulacaksınız – hem önceden planlama hem de sonrasında.',
        description: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Belgrad’ı keşfet: Görülmesi gereken yerler, alışveriş ve taksi uygulamaları',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: 'center',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h1',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Belgrad, Sırbistan’ın canlı başkenti, sizi etkileyici turistik yerler, büyüleyici bir kültür ve harika alışveriş imkanları ile karşılıyor. İşte konaklamanız sırasında mutlaka görmeniz gereken bazı önemli yerler:',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Kalemegdan Kalesi ve Parkı',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/Q15gp1b56zwxJk9r5',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d017e',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Tarihi kale, Tuna ve Sava nehirlerinin muhteşem manzarasını sunar ve güzel bir parkla çevrilidir – yürüyüş yapmak ve dinlenmek için mükemmel.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 1,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Skadarlija – Sanatçı Mahallesi',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/5LY3Rqs4wE1rEf9E8',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d017f',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Skadarlija, taş döşeli sokakları, geleneksel restoranları ve özel bir sanatçı atmosferi ile büyülüyor. Burada Belgrad’ın kültürünü yakından deneyimleyebilirsiniz.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 2,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Sveti Sava Katedrali',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://g.co/kgs/QuTW3Sc',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0180',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Dünyanın en büyük Ortodoks kilisesi, etkileyici bir simge ve ruhsal bir merkezdir, kesinlikle kaçırmamanız gereken bir yer.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 3,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Knez Mihailova Caddesi',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/GP7XoZ29xdsnAv1u5',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0181',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Bu hareketli yaya caddesi, dolaşmak ve alışveriş yapmak için idealdir ve birçok rahat kafe ve restoran sunar.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 4,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Galerija Alışveriş Merkezi',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://g.co/kgs/rQzisLq',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0183',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Balkan’ın en büyük alışveriş merkezi olan ',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Galerija Belgrade',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' uluslararası ve yerel markaların geniş bir yelpazesini, mükemmel restoranlar ve her yaş grubuna hitap eden eğlenceleri sunar – uzun bir alışveriş günü için mükemmel.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 5,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'list',
                version: 1,
                listType: 'bullet',
                start: 1,
                tag: 'ul',
              },
              {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 1,
                textStyle: '',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Belgrad’da Taksi: Doğru Uygulama',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h2',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Belgrad’da rahatça hareket edebilmeniz için ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Pink Taxi Uygulaması',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      doc: null,
                      linkType: 'custom',
                      newTab: false,
                      url: 'https://apps.apple.com/app/pink-taxi/id1459526702',
                    },
                    id: '67210ad5392660db554d0184',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' (',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'iOS',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://apps.apple.com/us/app/pink-taxi-beograd/id1446423607',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210ad5392660db554d0185',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' | ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Android',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://play.google.com/store/apps/details?id=com.autocab.taxibooker.pinktaxi.serbia&hl=de&pli=1',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210ad5392660db554d0186',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '). Uygulama, Belgrad’da taksi çağırmak için güvenilir ve emniyetli bir seçenektir. ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'İpucu:',
                    type: 'text',
                    version: 1,
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' Cumartesi günleri yüksek talep nedeniyle taksi bulmak zor olabilir – bu yüzden biraz zaman ayırmayı veya önceden rezervasyon yapmayı planlayın.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Bir diğer iyi seçenek ise ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Yandex Go Uygulaması',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      doc: null,
                      linkType: 'custom',
                      newTab: false,
                      url: 'https://yandex.com/',
                    },
                    id: '67210b2b392660db554d0188',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' (',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'iOS',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://apps.apple.com/de/app/yandex-go-taxi-food-delivery/id472650686',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210b2b392660db554d0189',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' | ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Android',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://play.google.com/store/apps/details?id=ru.yandex.taxi&hl=de',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210b2b392660db554d018a',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '), ayrıca sabit fiyatlar ve uygulama üzerinden kolay ödeme imkanı sunar.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                format: '',
                type: 'upload',
                version: 1,
                id: heroCouple.id,
                fields: null,
                relationTo: 'media',
                value: heroCouple.id,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      pariticipation: {
        title: 'Sizinle birlikte olmayı dört gözle bekliyoruz!',
        subtitle:
          'Lütfen burada kimin katılacağını ve kimin kuaför/makyaj için gelmek istediğini belirtin.',
        form: {
          participants: 'Katılımcılar',
          addParticipant: 'Katılımcı ekle',
          paricipantPlaceholder: 'Katılımcının adı',
          paricipantKidPlaceholder: 'Çocuğun adı',
          participantKid: 'Çocuk katılımcı (3 yaşına kadar)',
          addParticipantKid: 'Çocuk ekle',
          makeupHairInfo: 'Kişi başı 60€.',
          makeupHairPrice: 60,
          hairdresser: 'Kuaför',
          makeup: 'Makyaj',
          buttonText: 'Katılımı onayla',
          nameMissing: 'Lütfen bir isim girin.',
          unexpectedError:
            'Beklenmeyen bir hata oluştu. Lütfen bize WhatsApp üzerinden yazın veya bizi arayın.',
        },
        formSuccess: {
          backToStartPage: 'Ana sayfaya dön',
          title: 'Katılım onaylandı',
          subtitle:
            'Sizinle birlikte olmayı dört gözle bekliyoruz! Katılımınızla ilgili bir değişiklik olursa, lütfen bize haber verin.',
        },
      },
      countdown: {
        title: 'Yakında!',
        days: 'Gün',
        hours: 'Saat',
        minutes: 'Dakika',
        seconds: 'Saniye',
      },
      location: {
        image1: locationImage1.id,
        image2: locationImage2.id,
        image3: locationImage3.id,
        title: 'Mekan',
        name: 'Restoran Gardos',
        address: 'Grobljanska BB, Belgrad 11080, Sırbistan',
        buttonText: 'Google Haritalar',
        time: '17:00 - 01:00',
        mapsLink:
          'https://www.google.com/maps/place/Restaurant+Gardos/@44.848237,20.4044287,16z/data=!3m1!4b1!4m6!3m5!1s0x475a65a0fd0e7c1d:0xba29e72b79de3ac!8m2!3d44.8482371!4d20.409305!16s%2Fg%2F11c5zxfc_d?entry=ttu&g_ep=EgoyMDI0MTAxNi4wIKXMDSoASAFQAw%3D%3D',
      },
      footer: {
        title: 'Başka sorularınız mı var?',
        subtitle: 'Bizi arayın veya WhatsApp üzerinden bize yazın!',
      },
    },
    req,
  })

  payload.logger.info(`— Seeding start-page for sr...`)
  await payload.updateGlobal({
    slug: 'start-page',
    locale: 'sr',
    publishSpecificLocale: 'sr',
    data: {
      general: {
        weddingDate: '2025-06-14',
        participationDeadlineInformation:
          'Molimo vas da potvrdite svoje učešće do {{deadlineDate}}',
        participationDeadline: '2025-01-31',
        phoneNumber: '+49 4954 3450492',
      },
      start: {
        backgroundImage: heroCouple.id,
        title: 'Begum & Daniel',
        description: 'Radujemo se što ćemo podeliti naš poseban dan sa vama!',
        buttonText: 'Potvrdi učešće',
      },
      information: {
        title: 'Informacije',
        subtitle:
          'Ovde možete pronaći korisne informacije o glavnom gradu Srbije – kako za planiranje unapred, tako i za vreme nakon toga.',
        description: {
          root: {
            children: [
              {
                children: [
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Otkrijte Beograd: znamenitosti, šoping i taxi aplikacije',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: 'center',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h1',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Beograd, živahni glavni grad Srbije, očekuje vas sa impresivnim znamenitostima, fascinantnom kulturom i odličnim mogućnostima za šoping. Evo nekih istaknutih mesta koja obavezno treba da posetite tokom boravka:',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Kalemegdan tvrđava i park',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/Q15gp1b56zwxJk9r5',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d017e',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Istorijska tvrđava pruža vam impresivan pogled na Dunav i Savu i okružena je prelepim parkom – savršeno za šetnju i opuštanje',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 1,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Skadarlija – umetnička četvrt',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/5LY3Rqs4wE1rEf9E8',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d017f',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Skadarlija očarava kamenim pločama, tradicionalnim restoranima i posebnom umetničkom atmosferom. Ovde možete doživeti kulturu Beograda iz prve ruke.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 2,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Hram Svetog Save',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://g.co/kgs/QuTW3Sc',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0180',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Najveća pravoslavna crkva na svetu je impresivan simbol i duhovni centar koji nikako ne smete propustiti.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 3,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Knez Mihailova ulica',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://maps.app.goo.gl/GP7XoZ29xdsnAv1u5',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0181',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Ova užurbana pešačka zona je idealna za šetnju i šoping i nudi mnogo prijatnih kafića i restorana.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 4,
                  },
                  {
                    children: [
                      {
                        children: [
                          {
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Galerija Shopping Mall',
                            type: 'text',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        type: 'link',
                        version: 3,
                        fields: {
                          url: 'https://g.co/kgs/rQzisLq',
                          newTab: true,
                          linkType: 'custom',
                        },
                        id: '67210ad5392660db554d0183',
                      },
                      { type: 'linebreak', version: 1 },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' ',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Galerija Beograd',
                        type: 'text',
                        version: 1,
                      },
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: ' je najveći tržni centar na Balkanu i nudi vam ogroman izbor međunarodnih i lokalnih brendova, odlične restorane i zabavu za sve uzraste – savršeno za dan šopinga.',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'listitem',
                    version: 1,
                    value: 5,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'list',
                version: 1,
                listType: 'bullet',
                start: 1,
                tag: 'ul',
              },
              {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 1,
                textStyle: '',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Taxi u Beogradu: Prava aplikacija',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'heading',
                version: 1,
                tag: 'h2',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Da biste se lako kretali kroz Beograd, preporučujemo vam ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Pink Taxi aplikaciju',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      doc: null,
                      linkType: 'custom',
                      newTab: false,
                      url: 'https://apps.apple.com/app/pink-taxi/id1459526702',
                    },
                    id: '67210ad5392660db554d0184',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' (',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'iOS',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://apps.apple.com/us/app/pink-taxi-beograd/id1446423607',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210ad5392660db554d0185',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' | ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Android',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://play.google.com/store/apps/details?id=com.autocab.taxibooker.pinktaxi.serbia&hl=de&pli=1',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210ad5392660db554d0186',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '). Aplikacija je pouzdana i sigurna opcija za rezervaciju taksija u Beogradu. ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    detail: 0,
                    format: 1,
                    mode: 'normal',
                    style: '',
                    text: 'Saveta:',
                    type: 'text',
                    version: 1,
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' U subotu može biti teško dobiti taxi zbog velike potražnje – stoga je najbolje da planirate malo vremena ili rezervišete unapred.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Još jedan dobar izbor je ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Yandex Go aplikacija',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      doc: null,
                      linkType: 'custom',
                      newTab: false,
                      url: 'https://yandex.com/',
                    },
                    id: '67210b2b392660db554d0188',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' (',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'iOS',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://apps.apple.com/de/app/yandex-go-taxi-food-delivery/id472650686',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210b2b392660db554d0189',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: ' | ',
                    type: 'text',
                    version: 1,
                  },
                  {
                    children: [
                      {
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Android',
                        type: 'text',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    type: 'link',
                    version: 3,
                    fields: {
                      url: 'https://play.google.com/store/apps/details?id=ru.yandex.taxi&hl=de',
                      newTab: true,
                      linkType: 'custom',
                    },
                    id: '67210b2b392660db554d018a',
                  },
                  {
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: '), koja takođe nudi fiksne cene i jednostavno plaćanje putem aplikacije.',
                    type: 'text',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                children: [],
                direction: 'ltr',
                format: '',
                indent: 0,
                type: 'paragraph',
                version: 1,
                textFormat: 0,
                textStyle: '',
              },
              {
                format: '',
                type: 'upload',
                version: 1,
                id: heroCouple.id,
                fields: null,
                relationTo: 'media',
                value: heroCouple.id,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            type: 'root',
            version: 1,
          },
        },
      },
      pariticipation: {
        title: 'Radujemo se što ćete biti sa nama!',
        subtitle:
          'Molimo vas da ovde navedete ko će prisustvovati i ko želi da dođe na frizuru/šminku.',
        form: {
          participants: 'Učesnici',
          addParticipant: 'Dodaj učesnika',
          paricipantPlaceholder: 'Ime učesnika',
          paricipantKidPlaceholder: 'Ime deteta',
          participantKid: 'Dete učesnik (do 3 godine)',
          addParticipantKid: 'Dodaj dete',
          makeupHairInfo: '60€ po osobi.',
          makeupHairPrice: 60,
          hairdresser: 'Frizer',
          makeup: 'Šminka',
          buttonText: 'Potvrdi učešće',
          nameMissing: 'Molimo vas da unesete ime.',
          unexpectedError:
            'Došlo je do neočekivane greške. Molimo vas da nam pišete na WhatsApp ili nas pozovete.',
        },
        formSuccess: {
          backToStartPage: 'Nazad na početnu stranu',
          title: 'Učešće potvrđeno',
          subtitle:
            'Radujemo se što ćete biti sa nama! Ako se nešto promeni u vezi sa vašim učešćem, molimo vas da nas obavestite.',
        },
      },
      countdown: {
        title: 'Uskoro!',
        days: 'Dana',
        hours: 'Sati',
        minutes: 'Minuta',
        seconds: 'Sekundi',
      },
      location: {
        image1: locationImage1.id,
        image2: locationImage2.id,
        image3: locationImage3.id,
        title: 'Lokacija',
        name: 'Restoran Gardos',
        address: 'Grobljanska BB, Beograd 11080, Srbija',
        buttonText: 'Google mape',
        time: '17:00 - 01:00',
        mapsLink:
          'https://www.google.com/maps/place/Restaurant+Gardos/@44.848237,20.4044287,16z/data=!3m1!4b1!4m6!3m5!1s0x475a65a0fd0e7c1d:0xba29e72b79de3ac!8m2!3d44.8482371!4d20.409305!16s%2Fg%2F11c5zxfc_d?entry=ttu&g_ep=EgoyMDI0MTAxNi4wIKXMDSoASAFQAw%3D%3D',
      },
      footer: {
        title: 'Imate još pitanja?',
        subtitle: 'Pozovite nas ili nam pišite na WhatsApp!',
      },
    },
    req,
  })

  payload.logger.info('Seeded database successfully!')
}

async function uploadMedia({
  payload,
  req,
  fileName,
}: {
  payload: Payload
  req: PayloadRequest
  fileName: string
}) {
  return payload.create({
    collection: 'media',
    data: {},
    filePath: path.resolve(mediaFolder, fileName),
    req,
  })
}
